apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kcg2imiw2-python 
  janus-idp.io/tekton: kcg2imiw2-python
  backstage.io/kubernetes-id: kcg2imiw2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kcg2imiw2-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml